export type StockInfo = { name: string; symbol: string; market: string }

const KR_STOCKS: StockInfo[] = [
  // KOSPI 대형주
  { name: '삼성전자',       symbol: '005930', market: 'KOSPI' },
  { name: 'SK하이닉스',     symbol: '000660', market: 'KOSPI' },
  { name: 'LG에너지솔루션', symbol: '373220', market: 'KOSPI' },
  { name: '삼성바이오로직스',symbol: '207940', market: 'KOSPI' },
  { name: '현대차',         symbol: '005380', market: 'KOSPI' },
  { name: '기아',           symbol: '000270', market: 'KOSPI' },
  { name: 'POSCO홀딩스',    symbol: '005490', market: 'KOSPI' },
  { name: 'LG화학',         symbol: '051910', market: 'KOSPI' },
  { name: '삼성SDI',        symbol: '006400', market: 'KOSPI' },
  { name: 'KB금융',         symbol: '105560', market: 'KOSPI' },
  { name: '신한지주',       symbol: '055550', market: 'KOSPI' },
  { name: '하나금융지주',   symbol: '086790', market: 'KOSPI' },
  { name: '삼성물산',       symbol: '028260', market: 'KOSPI' },
  { name: '현대모비스',     symbol: '012330', market: 'KOSPI' },
  { name: 'LG전자',         symbol: '066570', market: 'KOSPI' },
  { name: '셀트리온',       symbol: '068270', market: 'KOSPI' },
  { name: 'SK이노베이션',   symbol: '096770', market: 'KOSPI' },
  { name: 'SK텔레콤',       symbol: '017670', market: 'KOSPI' },
  { name: 'KT&G',           symbol: '033780', market: 'KOSPI' },
  { name: '고려아연',       symbol: '010130', market: 'KOSPI' },
  { name: '삼성전기',       symbol: '009150', market: 'KOSPI' },
  { name: 'SK',             symbol: '034730', market: 'KOSPI' },
  { name: '롯데케미칼',     symbol: '011170', market: 'KOSPI' },
  { name: 'KT',             symbol: '030200', market: 'KOSPI' },
  { name: '두산에너빌리티', symbol: '034020', market: 'KOSPI' },
  { name: 'HD현대',         symbol: '267250', market: 'KOSPI' },
  { name: '한국전력',       symbol: '015760', market: 'KOSPI' },
  { name: '한화에어로스페이스', symbol: '012450', market: 'KOSPI' },
  { name: '삼성생명',       symbol: '032830', market: 'KOSPI' },
  { name: '우리금융지주',   symbol: '316140', market: 'KOSPI' },
  { name: '카카오',         symbol: '035720', market: 'KOSPI' },
  { name: 'NAVER',          symbol: '035420', market: 'KOSPI' },
  { name: '현대중공업',     symbol: '329180', market: 'KOSPI' },
  { name: '크래프톤',       symbol: '259960', market: 'KOSPI' },
  { name: '한국항공우주',   symbol: '047810', market: 'KOSPI' },
  { name: '아모레퍼시픽',   symbol: '090430', market: 'KOSPI' },
  { name: 'CJ제일제당',     symbol: '097950', market: 'KOSPI' },
  { name: '오리온',         symbol: '271560', market: 'KOSPI' },
  { name: '현대글로비스',   symbol: '086280', market: 'KOSPI' },
  { name: '녹십자',         symbol: '006280', market: 'KOSPI' },
  // KOSDAQ
  { name: 'HLB',            symbol: '028300', market: 'KOSDAQ' },
  { name: '에코프로',       symbol: '086520', market: 'KOSDAQ' },
  { name: '에코프로비엠',   symbol: '247540', market: 'KOSDAQ' },
  { name: '포스코DX',       symbol: '022100', market: 'KOSDAQ' },
  { name: '레인보우로보틱스',symbol: '277810', market: 'KOSDAQ' },
  { name: '알테오젠',       symbol: '196170', market: 'KOSDAQ' },
  { name: '리가켐바이오',   symbol: '141080', market: 'KOSDAQ' },
  { name: '클래시스',       symbol: '214150', market: 'KOSDAQ' },
  { name: '파크시스템스',   symbol: '140860', market: 'KOSDAQ' },
  { name: '카카오게임즈',   symbol: '293490', market: 'KOSDAQ' },
  // 국내 ETF — KODEX
  { name: 'KODEX 200',                      symbol: '069500', market: 'ETF' },
  { name: 'KODEX 코스닥150',                symbol: '229200', market: 'ETF' },
  { name: 'KODEX 반도체',                   symbol: '091160', market: 'ETF' },
  { name: 'KODEX 2차전지산업',              symbol: '305720', market: 'ETF' },
  { name: 'KODEX 미국S&P500',              symbol: '379800', market: 'ETF' },
  { name: 'KODEX 미국나스닥100',           symbol: '379810', market: 'ETF' },
  { name: 'KODEX 인버스',                   symbol: '114800', market: 'ETF' },
  { name: 'KODEX 레버리지',                 symbol: '122630', market: 'ETF' },
  { name: 'KODEX 국고채10년',              symbol: '148070', market: 'ETF' },
  { name: 'KODEX 골드선물(H)',             symbol: '132030', market: 'ETF' },
  { name: 'KODEX AI반도체핵심장비',        symbol: '396500', market: 'ETF' },
  // 국내 ETF — TIGER
  { name: 'TIGER 200',                      symbol: '102110', market: 'ETF' },
  { name: 'TIGER 미국S&P500',              symbol: '360750', market: 'ETF' },
  { name: 'TIGER 미국나스닥100',           symbol: '133690', market: 'ETF' },
  { name: 'TIGER 차이나CSI300',            symbol: '168580', market: 'ETF' },
  { name: 'TIGER 반도체',                   symbol: '091230', market: 'ETF' },
  { name: 'TIGER Fn반도체TOP10',          symbol: '381180', market: 'ETF' },
  { name: 'TIGER 2차전지테마',             symbol: '305540', market: 'ETF' },
  { name: 'TIGER 미국테크TOP10INDXX',     symbol: '381170', market: 'ETF' },
  { name: 'TIGER 글로벌리튬&2차전지SOLACTIVE', symbol: '371460', market: 'ETF' },
  // 국내 ETF — HANARO
  { name: 'HANARO 200',                     symbol: '293180', market: 'ETF' },
  { name: 'HANARO K-반도체',               symbol: '395270', market: 'ETF' },
  { name: 'HANARO K-반도체 ETF',          symbol: '395270', market: 'ETF' },
  { name: 'HANARO Fn K-반도체',            symbol: '395270', market: 'ETF' },
  { name: 'HANARO Fn K-반도체 ETF',       symbol: '395270', market: 'ETF' },
  { name: 'HANARO 미국빅테크TOP10INDXX',  symbol: '426410', market: 'ETF' },
  { name: 'HANARO 글로벌반도체TOP10INDXX',symbol: '427710', market: 'ETF' },
  // 국내 ETF — KINDEX / SOL / ACE
  { name: 'SOL 미국S&P500',               symbol: '433500', market: 'ETF' },
  { name: 'SOL 미국나스닥100',             symbol: '436450', market: 'ETF' },
  { name: 'ACE 미국S&P500',               symbol: '360200', market: 'ETF' },
  { name: 'ACE 미국나스닥100',             symbol: '367380', market: 'ETF' },
  { name: 'ACE KRX금현물',                symbol: '411060', market: 'ETF' },
  // 미국 주요 종목
  { name: 'Apple',          symbol: 'AAPL',   market: 'NASDAQ' },
  { name: 'Microsoft',      symbol: 'MSFT',   market: 'NASDAQ' },
  { name: 'NVIDIA',         symbol: 'NVDA',   market: 'NASDAQ' },
  { name: 'Amazon',         symbol: 'AMZN',   market: 'NASDAQ' },
  { name: 'Alphabet',       symbol: 'GOOGL',  market: 'NASDAQ' },
  { name: 'Meta',           symbol: 'META',   market: 'NASDAQ' },
  { name: 'Tesla',          symbol: 'TSLA',   market: 'NASDAQ' },
  { name: 'Broadcom',       symbol: 'AVGO',   market: 'NASDAQ' },
  { name: 'TSMC',           symbol: 'TSM',    market: 'NYSE' },
  { name: 'Samsung (ADR)',  symbol: 'SSNLF',  market: 'OTC' },
]

export function searchStocks(query: string): StockInfo[] {
  if (!query || query.length < 1) return []
  const q = query.toLowerCase()
  return KR_STOCKS.filter(
    s => s.name.toLowerCase().includes(q) || s.symbol.toLowerCase().includes(q)
  ).slice(0, 8)
}
